rvm:
  - 1.9.2
  - 1.9.3

branches:
  only:
    - master

env: 
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database basic_app_test;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database basic_app_test;' -U postgres; fi"
  - bundle exec rake config:database_settings
  - bundle exec rake db:schema:load RAILS_ENV=test

script: 'bundle exec rspec'
